version: '3.8'

services:
  backend: 
    image: 0202a2aca5b64121f4ab99d2ac166f08be2ae3a50d35db0e0f7f3bb82c1c02f0
    restart: always
    ports:  
      - 8080:8080
    volumes:
      - ./vue-ui/dist/index.html:/app/templates/index.html
      - ./vue-ui/dist/assets:/app/assets



# volumes:
